include: package:linteo/analysis_options.yaml

analyzer:
  plugins:
    - architecture_linter

architecture_linter:
  excludes:
    - "**.g.dart"

  lint_severity: warning

  layers:
    - &infrastructureLayer
      name: "Infrastructure"
      path: "(infrastructure)"
    - &domainLayer
      name: "Domain"
      path: "(domain)"
    - &presentationLayer
      name: "Presentation"
      path: "(presentation)"
    - &repository
      name: "repository"
      path: "(repository)"

  layers_config:
    - layer: *repository
      severity: info

  banned_imports:
    - layer: *domainLayer
      banned:
        - *presentationLayer
    - layer: *presentationLayer
      banned:
        - *infrastructureLayer
    - layer: *infrastructureLayer
      banned:
        - *presentationLayer
