name: example
description: A new Flutter project.
publish_to: 'none'
environment:
  sdk: ^3.0.0

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  architecture_linter:
    path: ../
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
